
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12000/eureka/
server:
  port: 12002
spring:
  application:
    name: service-auth
  redis:
      port: 6379
      timeout: 60
      jedis:
        pool:
          max-active: 1024
          max-idle: 200
          max-wait: 1000
          min-idle: 0
      host: 127.0.0.1
zuul:
  sensitive-headers:
  routes:
    service-user:
      serviceId: service-user
      path: /service-user/*
      #sensitive-headers:
      #custom-sensitive-headers: true
    service-blog:
      serviceId: service-blog
      path: /service-blog/*
      #sensitive-headers:
      #custom-sensitive-headers: true
  add-host-header: true